### ISSUE TITLE
Is ECS possible to build iOS application not a game？

### ISSUE THREAD

**Issue by wsof401** [fireblade-engine/ecs#1]

**Comment by ctreffs** [comment]
If I understand you correctly you like to know if the ECS may be used in an iOS application rather than in a game.

Since this is a pure swift package and it is a general purpose implementation of an entity-component system I see no problem with using it in any swift application what so ever.

I hope this helps.

Best regards,
@ctreffs

**Comment by wsof401** [comment]
yes, but how it works with UIKit or AppKit, That confuse me a lot

**Comment by ctreffs** [comment]
Here are three good reads about how to use entity-component systems in the context of app development. 

* https://github.com/sosolimited/Entity-Component-Samples/blob/master/README.md
* http://theliquidfire.com/2018/02/27/core-data-ecs/
* https://medium.com/@icex33/writing-apps-with-entitaskit-4a43a2f2a74b

These examples should apply to this ECS implementation. 
Maybe this helps to get you started.
